#!/usr/bin/env python3.6

import argparse
import whales


def setup():
    parser = argparse.ArgumentParser(description="dicker, cure your bad habit of mistyping docker.")
    parser.add_argument("-nc", "--no-color", help="disable color output", action="store_false")
    args = parser.parse_args()

    if args.no_color:
        from os import environ
        from colorama import init

        convert = None
        strip = None

        if 'PYCHARM_HOSTED' in environ:
            convert = False
            strip = False

        init(convert=convert, strip=strip)

    return args


def print_image(image):
    for string in image:
        print(string)


def main():
    args = setup()
    if args.no_color:
        print_image(whales.whale_color)
    else:
        print_image(whales.whale)


if __name__ == '__main__':
    main()
