#!/usr/bin/env python3.6

from os import environ

from colorama import init

import whales


def setup():
    convert = False
    strip = False

    if 'PYCHARM_HOSTED' in environ:
        convert = False
        strip = False

    init(convert=convert, strip=strip)


def print_image(image):
    for string in image:
        print(string)


def main():
    setup()
    print_image(whales.whale)
    print_image(whales.whale_color)


if __name__ == '__main__':
    main()
